version: "2.2"

services:
  django:
    image: "ghcr.io/open-contracting/pelican-frontend-django:latest"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # The container port must match the one exposed in the Dockerfile
    ports:
      - {{ pillar.docker_apps.pelican_frontend.port }}:8000
