# Based on: https://github.com/getnewdash/setup/blob/master/data/docker-compose.yml
version: "2.1"
x-redash-service: &redash-service
  image: redash/redash:10.0.0-beta.b49597
  depends_on:
    redis:
      condition: service_healthy
  env_file: /data/deploy/redash/.env
  extra_hosts:
    - "host.docker.internal:host-gateway"
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:6.2-alpine
    restart: always
    healthcheck:
      test: redis-cli -h 127.0.0.1 ping | grep -q PONG
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: redash/nginx:latest
    ports:
      - "9090:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
