version: "2.2"

x-shared: &shared
  image: "ghcr.io/open-contracting/data-registry-django:latest"
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-daemon: &daemon
  <<: *shared
  restart: unless-stopped

services:
  django:
    <<: *daemon
    ports: 
      - {{ pillar.docker_apps.registry.port }}:8000
  exporter:
    <<: *daemon
    command: "python manage.py exporter --settings=core.settings.docker"
    scale: 2
    # The right-hand path must match the settings.EXPORTER_DIR default value in data-registry.
    volumes:
      - /data/storage/exporter:/data/exporter
  wiper:
    <<: *daemon
    command: "python manage.py wiper --settings=core.settings.docker"

  cbom:
    <<: *shared
    command: "python manage.py cbom --settings=core.settings.docker"
    # The right-hand path must match the settings.KINGFISHER_COLLECT_FILES_STORE default value in data-registry.
    volumes:
      - {{ pillar.kingfisher_collect.env.FILES_STORE }}:/data/collect
  migrate:
    <<: *shared
    command: "python manage.py migrate --settings=core.settings.docker"

  static:
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    ports:
      - "8003:8080"
    restart: unless-stopped
