version: "2.2"

x-shared: &shared
  image: "ghcr.io/open-contracting/data-registry-django:latest"
  network_mode: "host"

x-daemon: &daemon
  <<: *shared
  restart: unless-stopped

services:
  django:
    <<: *daemon
    command: "./gunicorn_runner.sh {{ pillar.docker_apps.registry.port }}"
  exporter:
    <<: *daemon
    command: "python manage.py exporter --settings=core.settings.docker"
    scale: 2
    volumes:
      - /data/storage/exporter_dumps:/data/exporter_dumps
  wiper:
    <<: *daemon
    command: "python manage.py wiper --settings=core.settings.docker"

  cbom:
    <<: *shared
    command: "python manage.py cbom --settings=core.settings.docker"
    volumes:
      - {{ pillar.kingfisher_collect.files_store }}:/data/scrapy
  migrate:
    <<: *shared
    command: "python manage.py migrate --settings=core.settings.docker"

  static:
    image: "ghcr.io/open-contracting/data-registry-static:latest"
    ports:
      - "8003:8080"
    restart: unless-stopped
